### ISSUE TITLE
Type definition error "@material-ui/core@5.0.0-beta.2/Popper"

### ISSUE THREAD

**Issue by kamekyame** [ije/esm.sh#106]
https://esm.sh/@material-ui/core@5.0.0-beta.2/Popper

Deno gives the following type definition error:
```
error: TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'Instance'.
import { Instance, VirtualElement, Options, OptionsGeneric } from '/v47/@popperjs/core@2.9.3/dist/cjs/popper.d.ts';
         ~~~~~~~~
    at https://cdn.esm.sh/v47/@material-ui/core@5.0.0-beta.4/Popper/Popper.d.ts:2:10

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'VirtualElement'.
import { Instance, VirtualElement, Options, OptionsGeneric } from '/v47/@popperjs/core@2.9.3/dist/cjs/popper.d.ts';
                   ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@material-ui/core@5.0.0-beta.4/Popper/Popper.d.ts:2:20

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'Options'.
import { Instance, VirtualElement, Options, OptionsGeneric } from '/v47/@popperjs/core@2.9.3/dist/cjs/popper.d.ts';
                                   ~~~~~~~
    at https://cdn.esm.sh/v47/@material-ui/core@5.0.0-beta.4/Popper/Popper.d.ts:2:36

TS2305 [ERROR]: Module '"deno:///missing_dependency.d.ts"' has no exported member 'OptionsGeneric'.
import { Instance, VirtualElement, Options, OptionsGeneric } from '/v47/@popperjs/core@2.9.3/dist/cjs/popper.d.ts';
                                            ~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v47/@material-ui/core@5.0.0-beta.4/Popper/Popper.d.ts:2:45

Found 4 errors.
```

If you set import-map, the error disappears.

```json
{
  "imports": {
    "https://cdn.esm.sh/v47/@popperjs/core@2.9.3/dist/cjs/": "https://cdn.esm.sh/v47/@popperjs/core@2.9.3/lib/"
  }
}
```

**Comment by kamekyame** [comment]
I checked it for the first time in a while, and it was resolved, so I'm going to close it.
