### ISSUE TITLE
Failed to import -  react-icons

### ISSUE THREAD

**Issue by TiKevin83** [ije/esm.sh#208]
## Failing module

- **npm**: react-icons

```js
import { GoMarkGithub } from 'https://esm.sh/react-icons/go'
```

## Error message

Uncached or missing remote URL: "https://esm.sh/react-icons/go".deno(no-cache)
(React from esm.sh caches fine in my VS Code)

## Additional info

- **esm.sh version**: v57
- **Deno version**: 1.15.3

**Comment by marcushultman** [comment]
Getting this again now using `import { FaBeer } from 'https://esm.sh/react-icons@4.4.0/fa';`

esm.sh version: v94
Deno version: 1.25.0

**Comment by ije** [comment]
any error message？

**Comment by marcushultman** [comment]
@ije 
```
error: Uncaught SyntaxError: The requested module '/v95/react-icons@4.4.0/deno/lib/esm/iconContext.js' does not provide an export named 'DefaultContext'
    at <anonymous> (https://esm.sh/v95/react-icons@4.4.0/deno/lib/esm/iconBase.js:2:210)
```

**Comment by shishkin** [comment]
Getting the same error message with v102:

```
❯ deno run https://esm.sh/react-icons/fa
error: Uncaught SyntaxError: The requested module '/v102/react-icons@4.7.1/deno/lib/esm/iconContext.js' does not provide an export named 'DefaultContext'
    at <anonymous> (https://esm.sh/v102/react-icons@4.7.1/deno/lib/esm/iconBase.js:2:210)
```
