### ISSUE TITLE
Serves multiple conflicting versions of `@types/react` with `react` and `react-dom`

### ISSUE THREAD

**Issue by jaydenseric** [ije/esm.sh#331]
## Failing module

- **npm**: `react` + `react-dom`

```js
// @ts-check

import "https://esm.sh/react";
import "https://esm.sh/react-dom";
```

## Error message

After running `deno run` I got this:

```
Check file://[redacted]/demo.mjs
error: TS2300 [ERROR]: Duplicate identifier 'LibraryManagedAttributes'.
        type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
             ~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v78/@types/react@18.0.8/index.d.ts:3125:14

    'LibraryManagedAttributes' was also declared here.
            type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
                 ~~~~~~~~~~~~~~~~~~~~~~~~
        at https://cdn.esm.sh/v78/@types/react@18.0.6/index.d.ts:3121:14

TS2300 [ERROR]: Duplicate identifier 'LibraryManagedAttributes'.
        type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
             ~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v78/@types/react@18.0.6/index.d.ts:3121:14

    'LibraryManagedAttributes' was also declared here.
            type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
                 ~~~~~~~~~~~~~~~~~~~~~~~~
        at https://cdn.esm.sh/v78/@types/react@18.0.8/index.d.ts:3125:14

TS2717 [ERROR]: Subsequent property declarations must have the same type.  Property 'link' must be of type 'DetailedHTMLProps<LinkHTMLAttributes<HTMLLinkElement>, HTMLLinkElement>', but here has type 'DetailedHTMLProps<LinkHTMLAttributes<HTMLLinkElement>, HTMLLinkElement>'.
            link: React.DetailedHTMLProps<React.LinkHTMLAttributes<HTMLLinkElement>, HTMLLinkElement>;
            ~~~~
    at https://cdn.esm.sh/v78/@types/react@18.0.6/index.d.ts:3192:13

    'link' was also declared here.
                link: React.DetailedHTMLProps<React.LinkHTMLAttributes<HTMLLinkElement>, HTMLLinkElement>;
                ~~~~
        at https://cdn.esm.sh/v78/@types/react@18.0.8/index.d.ts:3196:13

Found 3 errors.
```

The root of the error can be seen using `deno info demo.mjs`:

```
local: /Users/jaydenseric/Projects/ruck-website/demo.mjs
type: Mjs
dependencies: 13 unique (total 1.29MB)

file://[redacted]/demo.mjs (80B)
├─┬ https://esm.sh/react (172B)
│ ├─┬ https://cdn.esm.sh/v78/@types/react@18.0.8/index.d.ts (150.28KB)
│ │ ├── https://cdn.esm.sh/v78/@types/react@18.0.8/global.d.ts (7.21KB)
│ │ ├── https://cdn.esm.sh/v78/@types/prop-types@15.7.5/index.d.ts (3.58KB)
│ │ ├── https://cdn.esm.sh/v78/@types/scheduler@0.16.2/tracing.d.ts (4.03KB)
│ │ └── https://cdn.esm.sh/v78/csstype@3.0.11/index.d.ts (850.38KB)
│ ├── https://cdn.esm.sh/v78/react@18.1.0/deno/react.js (8.42KB)
└─┬ https://esm.sh/react-dom (192B)
  ├─┬ https://cdn.esm.sh/v78/@types/react-dom@18.0.2/index.d.ts (3.82KB)
  │ └─┬ https://cdn.esm.sh/v78/@types/react@18.0.6/index.d.ts (150.09KB)
  │   ├── https://cdn.esm.sh/v78/@types/react@18.0.6/global.d.ts (7.21KB)
  │   ├── https://cdn.esm.sh/v78/@types/prop-types@15.7.5/index.d.ts *
  │   ├── https://cdn.esm.sh/v78/@types/scheduler@0.16.2/tracing.d.ts *
  │   └── https://cdn.esm.sh/v78/csstype@3.0.11/index.d.ts *
  ├─┬ https://cdn.esm.sh/v78/react-dom@18.1.0/deno/react-dom.js (128.75KB)
  │ ├── https://cdn.esm.sh/v78/react@18.1.0/deno/react.js *
  │ └── https://cdn.esm.sh/v78/scheduler@0.22.0/deno/scheduler.js (5.76KB)
```

As you can see, esm.sh is incorrectly serving multiple conflicting versions of `@types/react`.

## Additional info

- **esm.sh version**: Latest online
- **Deno version**: 1.21.2

**Comment by jimisaacs** [comment]
Just FYI I have been discussing this exact issue here https://github.com/esm-dev/esm.sh/issues/326, though I might have been conflating issues.

**Comment by ije** [comment]
now the server responses `x-typescript-types` with semver versioning, for example, `react@18` will use `https://esm.sh/v80/@types/react@^18/index.d.ts`, then `https://esm.sh/v80/@types/react@^18/index.d.ts` will redirect to `https://esm.sh/v80/react@18.0.9/index.d.ts`

**Comment by jaydenseric** [comment]
@ije there are still very strange things going on preventing React v18 being used with types.

If you have `demo.mjs`:

```js
// @ts-check

import "https://esm.sh/react-dom@18.2.0/client";
```

And run `deno info demo.mjs`:

```
local: [redacted]/demo.mjs
type: Mjs
dependencies: 6 unique (total 145.89KB)

file://[redacted]/demo.mjs (63B)
└─┬ https://esm.sh/react-dom@18.2.0/client (185B)
  ├─┬ https://esm.sh/v90/@types/react-dom@18.0.6/client~.d.ts (1.42KB)
  │ └── Relative import path "react" not prefixed with / or ./ or ../ (resolve error)
  ├─┬ https://esm.sh/v90/react-dom@18.2.0/deno/client.js (1.16KB)
  │ └─┬ https://esm.sh/v90/react-dom@18.2.0/deno/react-dom.js (128.91KB)
  │   ├── https://esm.sh/v90/react@18.2.0/deno/react.js (8.41KB)
  │   └── https://esm.sh/v90/scheduler@0.23.0/deno/scheduler.js (5.75KB)
```

Note the bare `react` import specifier in https://esm.sh/v90/@types/react-dom@18.0.6/client~.d.ts causing a resolve error.

I'm unable to get esm.sh work for React v18 and types in [Ruck](https://ruck.tech); the problem like my original issue is esm.sh is providing different conflicting versions of `@types/react` in the module graph.

With Deno config pointing to this import map:

```json
{
  "imports": {
    "free_port/": "https://deno.land/x/free_port@v1.2.0/",
    "graphql-react/": "https://unpkg.com/graphql-react@19.0.0/",
    "puppeteer": "https://deno.land/x/puppeteer@14.1.1/mod.ts",
    "react": "https://esm.sh/react@18.2.0?dev",
    "react-dom/client": "https://esm.sh/react-dom@18.2.0/client?dev",
    "react-dom/server": "https://esm.sh/react-dom@18.2.0/server?dev",
    "react-test-renderer": "https://esm.sh/react-test-renderer@18.2.0?dev",
    "react-waterfall-render/": "https://unpkg.com/react-waterfall-render@4.0.1/",
    "ruck/": "./",
    "std/": "https://deno.land/std@0.151.0/"
  }
}
```

Running `deno info hydrate.mjs` ([this module](https://github.com/jaydenseric/ruck/blob/v7.0.0/hydrate.mjs), but locally updated the imports etc. for React v18 and not yet pushed up to GitHub):

```
local: /Users/jaydenseric/Projects/ruck/hydrate.mjs
type: Mjs
dependencies: 73 unique (total 2.95MB)

file:///Users/jaydenseric/Projects/ruck/hydrate.mjs (2.37KB)
├─┬ file:///Users/jaydenseric/Projects/ruck/ClientProvider.mjs (8.31KB)
│ ├─┬ file:///Users/jaydenseric/Projects/ruck/Effect.mjs (498B)
│ │ ├─┬ https://esm.sh/react@18.2.0?dev (188B)
│ │ │ ├─┬ https://esm.sh/v90/@types/react@18.0.17/index.d.ts (150.57KB)
│ │ │ │ ├── https://esm.sh/v90/@types/react@18.0.17/global.d.ts (7.21KB)
│ │ │ │ ├── https://esm.sh/v90/@types/prop-types@15.7.5/index.d.ts (3.58KB)
│ │ │ │ ├── https://esm.sh/v90/@types/scheduler@0.16.2/tracing.d.ts (4.03KB)
│ │ │ │ └── https://esm.sh/v90/csstype@3.1.0/index.d.ts (851.41KB)
│ │ │ ├── https://esm.sh/v90/react@18.2.0/deno/react.development.js (74.02KB)
│ │ └── https://esm.sh/react@18.2.0?dev *
│ ├─┬ file:///Users/jaydenseric/Projects/ruck/HeadManager.mjs (3.1KB)
│ │ ├── https://esm.sh/react@18.2.0?dev *
│ │ └── https://esm.sh/react@18.2.0?dev *
│ ├─┬ file:///Users/jaydenseric/Projects/ruck/HeadManagerContext.mjs (272B)
│ │ ├── file:///Users/jaydenseric/Projects/ruck/HeadManager.mjs *
│ │ └── https://esm.sh/react@18.2.0?dev *
│ ├─┬ file:///Users/jaydenseric/Projects/ruck/NavigateContext.mjs (303B)
│ │ ├── file:///Users/jaydenseric/Projects/ruck/ClientProvider.mjs *
│ │ └── https://esm.sh/react@18.2.0?dev *
│ ├─┬ file:///Users/jaydenseric/Projects/ruck/RouteContext.mjs (256B)
│ │ ├─┬ file:///Users/jaydenseric/Projects/ruck/serve.mjs (11.8KB)
│ │ │ ├── file:///Users/jaydenseric/Projects/ruck/HeadManager.mjs *
│ │ │ ├── file:///Users/jaydenseric/Projects/ruck/HeadManager.mjs *
│ │ │ ├── file:///Users/jaydenseric/Projects/ruck/HeadManagerContext.mjs *
│ │ │ ├─┬ file:///Users/jaydenseric/Projects/ruck/Html.mjs (555B)
│ │ │ │ ├── file:///Users/jaydenseric/Projects/ruck/serve.mjs *
│ │ │ │ └── https://esm.sh/react@18.2.0?dev *
│ │ │ ├── file:///Users/jaydenseric/Projects/ruck/RouteContext.mjs *
│ │ │ ├─┬ file:///Users/jaydenseric/Projects/ruck/TransferContext.mjs (342B)
│ │ │ │ ├── file:///Users/jaydenseric/Projects/ruck/serve.mjs *
│ │ │ │ └── https://esm.sh/react@18.2.0?dev *
│ │ │ ├── file:///Users/jaydenseric/Projects/ruck/assertImportMap.mjs (3.14KB)
│ │ │ ├── file:///Users/jaydenseric/Projects/ruck/assertImportMap.mjs *
│ │ │ ├── file:///Users/jaydenseric/Projects/ruck/jsonToRawHtmlScriptValue.mjs (791B)
│ │ │ ├─┬ file:///Users/jaydenseric/Projects/ruck/publicFileResponse.mjs (2.46KB)
│ │ │ │ ├── file:///Users/jaydenseric/Projects/ruck/serve.mjs *
│ │ │ │ ├── https://deno.land/std@0.151.0/http/http_status.ts (9.97KB)
│ │ │ │ ├─┬ https://deno.land/std@0.151.0/media_types/mod.ts (11.85KB)
│ │ │ │ │ ├── https://deno.land/std@0.151.0/media_types/_util.ts (3.05KB)
│ │ │ │ │ └── https://deno.land/std@0.151.0/media_types/vendor/mime-db.v1.52.0.ts (182.13KB)
│ │ │ │ ├─┬ https://deno.land/std@0.151.0/path/mod.ts (877B)
│ │ │ │ │ ├── https://deno.land/std@0.151.0/_util/os.ts (632B)
│ │ │ │ │ ├── https://deno.land/std@0.151.0/path/_interface.ts (728B)
│ │ │ │ │ ├─┬ https://deno.land/std@0.151.0/path/common.ts (1.16KB)
│ │ │ │ │ │ └─┬ https://deno.land/std@0.151.0/path/separator.ts (259B)
│ │ │ │ │ │   └── https://deno.land/std@0.151.0/_util/os.ts *
│ │ │ │ │ ├─┬ https://deno.land/std@0.151.0/path/glob.ts (12.37KB)
│ │ │ │ │ │ ├── https://deno.land/std@0.151.0/_util/os.ts *
│ │ │ │ │ │ ├── https://deno.land/std@0.151.0/_util/os.ts *
│ │ │ │ │ │ ├─┬ https://deno.land/std@0.151.0/path/posix.ts (14.65KB)
│ │ │ │ │ │ │ ├── https://deno.land/std@0.151.0/path/_constants.ts (1.97KB)
│ │ │ │ │ │ │ ├── https://deno.land/std@0.151.0/path/_interface.ts *
│ │ │ │ │ │ │ └─┬ https://deno.land/std@0.151.0/path/_util.ts (3.69KB)
│ │ │ │ │ │ │   ├── https://deno.land/std@0.151.0/path/_constants.ts *
│ │ │ │ │ │ │   └── https://deno.land/std@0.151.0/path/_interface.ts *
│ │ │ │ │ │ ├── https://deno.land/std@0.151.0/path/separator.ts *
│ │ │ │ │ │ └─┬ https://deno.land/std@0.151.0/path/win32.ts (29.19KB)
│ │ │ │ │ │   ├── https://deno.land/std@0.151.0/_util/assert.ts (443B)
│ │ │ │ │ │   ├── https://deno.land/std@0.151.0/path/_constants.ts *
│ │ │ │ │ │   ├── https://deno.land/std@0.151.0/path/_interface.ts *
│ │ │ │ │ │   └── https://deno.land/std@0.151.0/path/_util.ts *
│ │ │ │ │ ├── https://deno.land/std@0.151.0/path/posix.ts *
│ │ │ │ │ ├── https://deno.land/std@0.151.0/path/separator.ts *
│ │ │ │ │ └── https://deno.land/std@0.151.0/path/win32.ts *
│ │ │ │ └─┬ https://deno.land/std@0.151.0/streams/conversion.ts (17.03KB)
│ │ │ │   └─┬ https://deno.land/std@0.151.0/io/buffer.ts (30.87KB)
│ │ │ │     ├── https://deno.land/std@0.151.0/_util/assert.ts *
│ │ │ │     ├── https://deno.land/std@0.151.0/bytes/bytes_list.ts (4KB)
│ │ │ │     ├─┬ https://deno.land/std@0.151.0/bytes/mod.ts (7.37KB)
│ │ │ │     │ └── https://deno.land/std@0.151.0/bytes/equals.ts (1.47KB)
│ │ │ │     └── https://deno.land/std@0.151.0/io/types.d.ts (3.3KB)
│ │ │ ├─┬ file:///Users/jaydenseric/Projects/ruck/readImportMapFile.mjs (1.24KB)
│ │ │ │ ├── file:///Users/jaydenseric/Projects/ruck/assertImportMap.mjs *
│ │ │ │ └── file:///Users/jaydenseric/Projects/ruck/assertImportMap.mjs *
│ │ │ ├── https://unpkg.com/graphql-react@19.0.0/Cache.mjs (2.52KB)
│ │ │ ├─┬ https://unpkg.com/graphql-react@19.0.0/CacheContext.mjs (410B)
│ │ │ │ ├── https://unpkg.com/graphql-react@19.0.0/Cache.mjs *
│ │ │ │ └── https://esm.sh/react@18.2.0?dev *
│ │ │ ├─┬ https://unpkg.com/graphql-react@19.0.0/Loading.mjs (1.7KB)
│ │ │ │ ├── https://unpkg.com/graphql-react@19.0.0/Cache.mjs *
│ │ │ │ └─┬ https://unpkg.com/graphql-react@19.0.0/LoadingCacheValue.mjs (4.38KB)
│ │ │ │   ├── https://unpkg.com/graphql-react@19.0.0/Cache.mjs *
│ │ │ │   ├── https://unpkg.com/graphql-react@19.0.0/Cache.mjs *
│ │ │ │   ├── https://unpkg.com/graphql-react@19.0.0/Loading.mjs *
│ │ │ │   ├── https://unpkg.com/graphql-react@19.0.0/Loading.mjs *
│ │ │ │   └─┬ https://unpkg.com/graphql-react@19.0.0/cacheEntrySet.mjs (868B)
│ │ │ │     ├── https://unpkg.com/graphql-react@19.0.0/Cache.mjs *
│ │ │ │     └── https://unpkg.com/graphql-react@19.0.0/Cache.mjs *
│ │ │ ├─┬ https://unpkg.com/graphql-react@19.0.0/LoadingContext.mjs (428B)
│ │ │ │ ├── https://unpkg.com/graphql-react@19.0.0/Loading.mjs *
│ │ │ │ └── https://esm.sh/react@18.2.0?dev *
│ │ │ ├── https://esm.sh/react@18.2.0?dev *
│ │ │ ├── https://esm.sh/react@18.2.0?dev *
│ │ │ ├─┬ https://esm.sh/react-dom@18.2.0/server?dev (209B)
│ │ │ │ ├─┬ https://esm.sh/v90/@types/react-dom@18.0.6/server~.d.ts (4.1KB)
│ │ │ │ │ └─┬ https://esm.sh/v90/@types/react@18.0.15/index.d.ts (150.57KB)
│ │ │ │ │   ├── https://esm.sh/v90/@types/react@18.0.15/global.d.ts (7.21KB)
│ │ │ │ │   ├── https://esm.sh/v90/@types/prop-types@15.7.5/index.d.ts *
│ │ │ │ │   ├── https://esm.sh/v90/@types/scheduler@0.16.2/tracing.d.ts *
│ │ │ │ │   └── https://esm.sh/v90/csstype@3.1.0/index.d.ts *
│ │ │ │ ├─┬ https://esm.sh/v90/react-dom@18.2.0/deno/server.development.js (440.78KB)
│ │ │ │ │ └── https://esm.sh/v90/react@18.2.0/deno/react.development.js *
│ │ │ ├─┬ https://unpkg.com/react-waterfall-render@4.0.1/waterfallRender.mjs (4.7KB)
│ │ │ │ ├─┬ https://unpkg.com/react-waterfall-render@4.0.1/WaterfallRenderContext.mjs (1.01KB)
│ │ │ │ │ ├── https://unpkg.com/react-waterfall-render@4.0.1/waterfallRender.mjs *
│ │ │ │ │ └── https://esm.sh/react@18.2.0?dev *
│ │ │ │ └── https://esm.sh/react@18.2.0?dev *
│ │ │ ├── https://deno.land/std@0.151.0/http/http_status.ts *
│ │ │ ├─┬ https://deno.land/std@0.151.0/http/server.ts (22.94KB)
│ │ │ │ └─┬ https://deno.land/std@0.151.0/async/mod.ts (460B)
│ │ │ │   ├─┬ https://deno.land/std@0.151.0/async/abortable.ts (2KB)
│ │ │ │   │ └── https://deno.land/std@0.151.0/async/deferred.ts (1.49KB)
│ │ │ │   ├─┬ https://deno.land/std@0.151.0/async/deadline.ts (618B)
│ │ │ │   │ └── https://deno.land/std@0.151.0/async/deferred.ts *
│ │ │ │   ├── https://deno.land/std@0.151.0/async/debounce.ts (2.08KB)
│ │ │ │   ├── https://deno.land/std@0.151.0/async/deferred.ts *
│ │ │ │   ├── https://deno.land/std@0.151.0/async/delay.ts (827B)
│ │ │ │   ├─┬ https://deno.land/std@0.151.0/async/mux_async_iterator.ts (1.96KB)
│ │ │ │   │ └── https://deno.land/std@0.151.0/async/deferred.ts *
│ │ │ │   ├── https://deno.land/std@0.151.0/async/pool.ts (2.83KB)
│ │ │ │   └── https://deno.land/std@0.151.0/async/tee.ts (2.13KB)
│ │ │ └── https://deno.land/std@0.151.0/path/mod.ts *
│ │ └── https://esm.sh/react@18.2.0?dev *
│ ├── file:///Users/jaydenseric/Projects/ruck/scrollToHash.mjs (482B)
│ ├── file:///Users/jaydenseric/Projects/ruck/serve.mjs *
│ ├── https://unpkg.com/graphql-react@19.0.0/Cache.mjs *
│ ├── https://unpkg.com/graphql-react@19.0.0/CacheContext.mjs *
│ ├─┬ https://unpkg.com/graphql-react@19.0.0/HydrationTimeStampContext.mjs (471B)
│ │ └── https://esm.sh/react@18.2.0?dev *
│ ├── https://unpkg.com/graphql-react@19.0.0/Loading.mjs *
│ ├── https://unpkg.com/graphql-react@19.0.0/LoadingContext.mjs *
│ ├── https://esm.sh/react@18.2.0?dev *
│ └── https://esm.sh/react@18.2.0?dev *
├─┬ file:///Users/jaydenseric/Projects/ruck/HeadContent.mjs (1.11KB)
│ ├── file:///Users/jaydenseric/Projects/ruck/HeadManager.mjs *
│ └── https://esm.sh/react@18.2.0?dev *
├── file:///Users/jaydenseric/Projects/ruck/HeadManager.mjs *
├── file:///Users/jaydenseric/Projects/ruck/createPseudoNode.mjs (3.05KB)
├── file:///Users/jaydenseric/Projects/ruck/serve.mjs *
├── https://unpkg.com/graphql-react@19.0.0/Cache.mjs *
├── https://unpkg.com/graphql-react@19.0.0/Loading.mjs *
├── https://esm.sh/react@18.2.0?dev *
└─┬ https://esm.sh/react-dom@18.2.0/client?dev (209B)
  ├─┬ https://esm.sh/v90/@types/react-dom@18.0.6/client~.d.ts (1.42KB)
  │ └── https://esm.sh/react@18.2.0?dev *
  ├─┬ https://esm.sh/v90/react-dom@18.2.0/deno/client.development.js (2.74KB)
  │ └─┬ https://esm.sh/v90/react-dom@18.2.0/deno/react-dom.development.js (869.51KB)
  │   ├── https://esm.sh/v90/react@18.2.0/deno/react.development.js *
  │   └── https://esm.sh/v90/scheduler@0.23.0/deno/scheduler.development.js (19.66KB)
```

Note these incorrectly both appear in the graph:

- https://esm.sh/v90/@types/react@18.0.15/index.d.ts
- https://esm.sh/v90/@types/react@18.0.17/index.d.ts

**Comment by jaydenseric** [comment]
With `demo.mjs`:

```js
// @ts-check

import "https://esm.sh/react@18.2.0?dev";
import "https://esm.sh/react-dom@18.2.0/server?dev";
```

Run:

```
deno check --remote demo.mjs
```

And note the errors:

```
Check file://[redacted]/demo.mjs
error: TS2300 [ERROR]: Duplicate identifier 'LibraryManagedAttributes'.
        type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
             ~~~~~~~~~~~~~~~~~~~~~~~~
    at https://esm.sh/v92/@types/react@18.0.18/index.d.ts:3131:14

    'LibraryManagedAttributes' was also declared here.
            type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
                 ~~~~~~~~~~~~~~~~~~~~~~~~
        at https://esm.sh/v92/@types/react@18.0.17/index.d.ts:3131:14

TS2300 [ERROR]: Duplicate identifier 'LibraryManagedAttributes'.
        type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
             ~~~~~~~~~~~~~~~~~~~~~~~~
    at https://esm.sh/v92/@types/react@18.0.17/index.d.ts:3131:14

    'LibraryManagedAttributes' was also declared here.
            type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
                 ~~~~~~~~~~~~~~~~~~~~~~~~
        at https://esm.sh/v92/@types/react@18.0.18/index.d.ts:3131:14

Found 2 errors.
```

If you run:

```
deno info demo.mjs
```

You can see that esm.sh is incorrectly loading multiple versions of `@types/react`, causing broken types:

```
local: [redacted]/demo.mjs
type: Mjs
dependencies: 12 unique (total 1.65MB)

file://[redacted]/demo.mjs (109B)
├─┬ https://esm.sh/react-dom@18.2.0/server?dev (209B)
│ ├─┬ https://esm.sh/v92/@types/react-dom@18.0.6/server~.d.ts (4.1KB)
│ │ └─┬ https://esm.sh/v92/@types/react@18.0.17/index.d.ts (150.57KB)
│ │   ├── https://esm.sh/v92/@types/react@18.0.17/global.d.ts (7.21KB)
│ │   ├── https://esm.sh/v92/@types/prop-types@15.7.5/index.d.ts (3.58KB)
│ │   ├── https://esm.sh/v92/@types/scheduler@0.16.2/tracing.d.ts (4.03KB)
│ │   └── https://esm.sh/v92/csstype@3.1.0/index.d.ts (851.41KB)
│ ├─┬ https://esm.sh/v92/react-dom@18.2.0/deno/server.development.js (440.8KB)
│ │ └── https://esm.sh/stable/react@18.2.0/deno/react.development.js (74.04KB)
└─┬ https://esm.sh/react@18.2.0?dev (194B)
  ├─┬ https://esm.sh/v92/@types/react@18.0.18/index.d.ts (150.57KB)
  │ ├── https://esm.sh/v92/@types/react@18.0.18/global.d.ts (7.21KB)
  │ ├── https://esm.sh/v92/@types/prop-types@15.7.5/index.d.ts *
  │ ├── https://esm.sh/v92/@types/scheduler@0.16.2/tracing.d.ts *
  │ └── https://esm.sh/v92/csstype@3.1.0/index.d.ts *
  ├── https://esm.sh/stable/react@18.2.0/deno/react.development.js *
```

I'm flabbergasted this is still problematic, am I the only human being trying to use React v18 with Deno and type safety for the past 4 months? Maybe I am 😢

**Comment by ije** [comment]
try to clean the deno cache, v90 responses unexpected types that has been fixed in v91

**Comment by jaydenseric** [comment]
The cache is clean; please just try [the minimal reproduction](https://github.com/ije/esm.sh/issues/331#issuecomment-1235110596) yourself. You can also see this CI failure: https://github.com/jaydenseric/ruck/runs/8150593351?check_suite_focus=true
