### ISSUE TITLE
Failed to import memfs with typechecking

### ISSUE THREAD

**Issue by espindola** [ije/esm.sh#363]
Trying to import

```
import 'https://esm.sh/memfs@3.4.7?target=deno'
```

with

```
deno run --check=all --reload  test.ts
```

fails with

```
error: TS2300 [ERROR]: Duplicate identifier 'URLSearchParams'.
declare class URLSearchParams {
              ~~~~~~~~~~~~~~~
    at asset:///lib.deno.url.d.ts:8:15

    'URLSearchParams' was also declared here.
            interface URLSearchParams extends _URLSearchParams {}
                      ~~~~~~~~~~~~~~~
        at https://esm.sh/v86/@types/node@16.11.33/url.d.ts:822:19    and here.
....
```

This is surprisingly hard to reduce. I downloaded the code with

```
$ curl -o foo.js -Dheader 'https://esm.sh/memfs@3.4.7?target=deno'
```

and changed the test to

```
// @deno-types="https://esm.sh/v86/memfs@3.4.7/lib/index.d.ts"
import './foo.js'
```

But this changes the error to

```
error: Relative import path "querystring" not prefixed with / or ./ or ../
    at https://esm.sh/v86/@types/node@16.11.33/querystring.d.ts:131:19
```

The last one at least is easy to see, line 131 has:

```
 export * from 'querystring';
```

**Comment by espindola** [comment]
> seems the types is incorrect, you can disable it by `?no-check`

Yes, or just not passing `--check` to deno. I have updated the description to say that the issue is with the .d.ts files, the .js is fine.
