### ISSUE TITLE
Failed to import - twind and @twind/preset-tailwind-forms because of regression in esm.sh v88

### ISSUE THREAD

**Issue by KyleJune** [ije/esm.sh#395]
## Failing module

- **GitHub**: https://github.com/tw-in-js/twind/blob/v1.0.0-next.38/packages/preset-tailwind-forms/
- **npm**: https://www.npmjs.com/package/@twind/preset-tailwind-forms/v/1.0.0-next.38

This example comes from the readme. The one difference being that I had to cast as any because the types are getting messed up by esm.sh. I know this because I was able to get the package working with v85 of esm.sh with just a slight modification of one file which can be found [here](https://github.com/ije/esm.sh/issues/325#issuecomment-1126989846).

```js
import { setup } from "https://esm.sh/twind@1.0.0-next.38?target=deno&pin=v90";
import presetTailwind from "https://esm.sh/@twind/preset-tailwind@1.0.0-next.38?target=deno&pin=v90";
import presetTailwindForms from "https://esm.sh/@twind/preset-tailwind-forms@1.0.0-next.38?target=deno&pin=v90";

setup({
  // deno-lint-ignore no-explicit-any
  presets: [presetTailwind(/* options */), presetTailwindForms(/* options */)] as any,
  /* config */
})
```

## Error message

After running `deno run` I got this:

```
error: Uncaught TypeError: Cannot read properties of undefined (reading 'base')
    at https://esm.sh/v90/@twind/preset-tailwind-forms@1.0.0-next.38/deno/preset-tailwind-forms.js:2:2077
    at https://esm.sh/v90/@twind/preset-tailwind-forms@1.0.0-next.38/deno/preset-tailwind-forms.js:2:1309
    at https://esm.sh/v90/@twind/preset-tailwind-forms@1.0.0-next.38/deno/preset-tailwind-forms.js:2:7582
```

## Additional info

- **esm.sh version**: v90
- **Deno version**: 1.24.1

I tried updating the version of esm.sh to see where this broke, it looks like it broke in v88 because it gets the same error and v87 doesn't get the error.

Here is what you get if you run deno info.

```
deno info example.ts
local: /home/kyle/Projects/deno/udibo/esm_issue/example.ts
type: TypeScript
dependencies: 13 unique (total 971.96KB)

file:///home/kyle/Projects/deno/udibo/esm_issue/example.ts (447B)
├─┬ https://esm.sh/@twind/preset-tailwind-forms@1.0.0-next.38?target=deno&pin=v90 (286B)
│ ├─┬ https://esm.sh/v90/@twind/preset-tailwind-forms@1.0.0-next.38/preset-tailwind-forms.d.ts (594B)
│ │ ├─┬ https://esm.sh/v90/@twind/preset-tailwind@1.0.0-next.38/preset-tailwind.d.ts (7.73KB)
│ │ │ └── Relative import path "twind" not prefixed with / or ./ or ../ (resolve error)
│ │ └─┬ https://esm.sh/v90/twind@1.0.0-next.38/twind.d.ts (33.02KB)
│ │   └── https://esm.sh/v90/csstype@3.1.0/index.d.ts (851.41KB)
│ ├─┬ https://esm.sh/v90/@twind/preset-tailwind-forms@1.0.0-next.38/deno/preset-tailwind-forms.js (7.56KB)
│ │ ├─┬ https://esm.sh/v90/@twind/preset-tailwind@1.0.0-next.1/deno/defaultTheme.js (7.9KB)
│ │ │ └── https://esm.sh/v90/@twind/preset-tailwind@1.0.0-next.1/deno/colors.js (3.37KB)
│ │ ├── https://esm.sh/v90/@twind/preset-tailwind@1.0.0-next.38/deno/colors.js (5.92KB)
│ │ └── https://esm.sh/v90/twind@1.0.0-next.38/deno/twind.js (21.44KB)
├─┬ https://esm.sh/@twind/preset-tailwind@1.0.0-next.38?target=deno&pin=v90 (256B)
│ ├── https://esm.sh/v90/@twind/preset-tailwind@1.0.0-next.38/preset-tailwind.d.ts *
│ ├─┬ https://esm.sh/v90/@twind/preset-tailwind@1.0.0-next.38/deno/preset-tailwind.js (31.88KB)
│ │ └── https://esm.sh/v90/twind@1.0.0-next.38/deno/twind.js *
└─┬ https://esm.sh/twind@1.0.0-next.38?target=deno&pin=v90 (185B)
  ├── https://esm.sh/v90/twind@1.0.0-next.38/twind.d.ts *
  ├── https://esm.sh/v90/twind@1.0.0-next.38/deno/twind.js *
```

One thing worth noting in this is that `preset-tailwind-forms.js` ends up importing the wrong version of `defaultTheme.js` but not `colors.js`. If you look at the [package.json](https://github.com/tw-in-js/twind/blob/v1.0.0-next.38/packages/preset-tailwind-forms/package.json), preset-tailwind-forms should be using `@twind/preset-tailwind@1.0.0-next.38`. If you look at the [original file](https://github.com/tw-in-js/twind/blob/v1.0.0-next.38/packages/preset-tailwind-forms/src/preset-tailwind-forms.ts), you'll find the following is how they import those 2 dependencies. The version it is using for `@twind/preset-tailwind/defaultTheme` is the current latest release instead of what the `package.json` says to use.

```ts
import * as colors from '@twind/preset-tailwind/colors'
import defaultTheme from '@twind/preset-tailwind/defaultTheme'
```

If I add an import map for mapping `https://esm.sh/v90/@twind/preset-tailwind@1.0.0-next.1/deno/defaultTheme.js` to `https://esm.sh/v90/@twind/preset-tailwind@1.0.0-next.38/deno/defaultTheme.js` it fixes that version mix up but does not fix the error. This issue was also present in v85 when I last had this module working.

Another thing worth noting is the relative import path resolve error in `preset-tailwind.d.ts`. This issue was around and is not causing the type issue. I did not have a type issue with v85 but it looks like I have a type issue in all the versions after that. Here is a screenshot of the warning I get in vs code.

![image](https://user-images.githubusercontent.com/3241653/183274346-32a537dc-5cd5-4f45-94a6-2a1f800c5e06.png)
![image](https://user-images.githubusercontent.com/3241653/183274397-c31d5c12-1889-4e7f-916f-14d357eefe19.png)

Here is what hovering over setup shows when using the last working version of esm.sh (v85).

![image](https://user-images.githubusercontent.com/3241653/183274453-f32f1d89-faf2-4099-9d73-86423d3848dd.png)

If you look at the [original file](https://github.com/tw-in-js/twind/blob/v1.0.0-next.38/packages/twind/src/runtime.ts#L86), the time it was working matched the second call signature. The time it fails it thinks I'm using the first call signature.

In both v85 and v90 of esm.sh, it appears both the preset functions are returning values of the type `Preset<TailwindTheme>`. So even though the object passed into setup has the same type as before, it ends up thinking I'm calling setup with the wrong call signature. It might have to do with the wrong call signature being the first one.

As for the runtime error provided at the top of this issue, I was able to find the cause and apply a manual fix, but the module still didn't work right afterward, it just stopped throwing an error. So I don't think my manual fix was the correct fix. A detailed explanation can be found in [this comment](https://github.com/ije/esm.sh/issues/325#issuecomment-1200536128) on another issue. I created this new issue because this issue is different than what that previous issue was created for.

**Comment by KyleJune** [comment]
This is still an issue in v95.
