### ISSUE TITLE
Failed to import - postcss-nested

### ISSUE THREAD

**Issue by kidonng** [ije/esm.sh#411]
## Failing module

- **GitHub**: https://github.com/postcss/postcss-nested
- **npm**: https://www.npmjs.com/package/postcss-nested

```js
import postcss from 'https://esm.sh/postcss@8.4.16'
import nested from 'https://esm.sh/postcss-nested@5.0.6'

const {css} = postcss([nested]).process(`
.a {
	color: blue;

	& .b {
		color: red;
	}
}
`)

console.log(css)
```

## Error message

After running `deno run` I got this:

```
error: Uncaught TypeError: _ is not a function
    at v (https://esm.sh/v92/postcss-nested@5.0.6/deno/postcss-nested.js:2:998)
    at https://esm.sh/v92/postcss-nested@5.0.6/deno/postcss-nested.js:2:1397
    at Array.forEach (<anonymous>)
    at x (https://esm.sh/v92/postcss-nested@5.0.6/deno/postcss-nested.js:2:1379)
    at https://esm.sh/v92/postcss-nested@5.0.6/deno/postcss-nested.js:2:2454
    at https://esm.sh/v92/postcss@8.4.16/deno/postcss.js:24:5129
    at M.each (https://esm.sh/v92/postcss@8.4.16/deno/postcss.js:24:1199)
    at Proxy.<anonymous> (https://esm.sh/v92/postcss@8.4.16/deno/postcss.js:24:5088)
    at Rule (https://esm.sh/v92/postcss-nested@5.0.6/deno/postcss-nested.js:2:2365)
    at C.visitSync (https://esm.sh/v92/postcss@8.4.16/deno/postcss.js:26:11276)
```

## Additional info

- **esm.sh version**: v92
- **Deno version**: 1.25.0

I noticed the following code:

```js
let parser = require('postcss-selector-parser')
```

...is transformed into:

```js
import * as __postcss_selector_parser$ from "/v92/postcss-selector-parser@6.0.10/deno/postcss-selector-parser.js";
```

Which is not correct all the time, for example when the default export is a function with properties. `postcss-nested` uses both of them:

```js
  // This is where error happens
  let saver = parser(parsed => {
    nodes = parsed
  })

// ...

node.prepend(parser.combinator({ value: ' ' }))
```

In comparison, Skypack is transforming is correctly:

```js
// https://cdn.skypack.dev/-/postcss-nested@v5.0.6-3jtl1woHVKZJRFV88dAO/dist=es2019,mode=imports/optimized/postcss-nested.js
import parser from "/-/postcss-selector-parser@v6.0.8-Zc9iHxeGLamtrCkJSf9w/dist=es2019,mode=imports/optimized/postcss-selector-parser.js";
```

**Comment by kidonng** [comment]
@ije Kindly ping because I feel this is a serious issue. I also tried past versions, and got the same error since v72 (well, v71 does give the same transformed import, but a new error appeared).

**Comment by kidonng** [comment]
I see, so there's a hard-coded list fixing these errors. I wish we can have a better solution in the future.

In the meantime, you may want to also add `conf` into the list, which is reported in #410.
