### ISSUE TITLE
Failed to import - https://esm.sh/knex@2.2.0

### ISSUE THREAD

**Issue by vanpipy** [ije/esm.sh#413]
## Failing module

- **GitHub**:  https://github.com/knex/knex
- **npm**: https://www.npmjs.com/package/knex

```js
import knex from 'https://esm.sh/knex@2.2.0';
```

## Error message

After running `deno run` I got this:

![image](https://user-images.githubusercontent.com/7385872/187398800-f74f7754-3c39-4fca-9095-cac32511a50a.png)

```
error: Uncaught (in promise) Error: /home/leroy/Project/bookish/https:/esm.sh/v92/sqlite3@5.0.11/package.jsondoes not exist
    at Object.x.find (https://esm.sh/v92/@mapbox/node-pre-gyp@1.0.9/deno/node-pre-gyp.js:6:2489)
    at https://esm.sh/v92/sqlite3@5.0.11/deno/sqlite3.js:2:1232
    at https://esm.sh/v92/sqlite3@5.0.11/deno/sqlite3.js:2:853
    at https://esm.sh/v92/sqlite3@5.0.11/deno/sqlite3.js:7:132
    at https://esm.sh/v92/sqlite3@5.0.11/deno/sqlite3.js:2:853
    at https://esm.sh/v92/sqlite3@5.0.11/deno/sqlite3.js:7:2686
```

## Additional info

- **esm.sh version**:  Unknown
- **Deno version**:
```
deno 1.25.0 (release, x86_64-unknown-linux-gnu)
v8 10.6.194.5
typescript 4.7.4
```
- Failed to import the versions 2.0.0, 2.1.0, 2.2.0 of the knex, it looks like no one version can satisfy the import rule.

**Comment by vanpipy** [comment]
Did the `knex` not support use by `deno`?  Because I found this one `knex` [issue](https://github.com/knex/knex/issues/3851).
