### ISSUE TITLE
Failed to import - https://esm.sh/v94/fsevents@2.3.2/deno/fsevents.js

### ISSUE THREAD

**Issue by UPL123** [ije/esm.sh#419]
## Failing module

- **GitHub**: https://github.com/fsevents/fsevents
- **npm**: https://www.npmjs.com/package/fsevents

```js
import {
  generateSW,
  GenerateSWOptions,
} from "https://esm.sh/workbox-build@6.5.4";
// Downloads dependency fsevents from https://esm.sh/v94/fsevents@2.3.2/deno/fsevents.js
```

## Error message

After running `deno run` I got this:

```
error: Uncaught Error: The filename, directory name, or volume label syntax is not correct. (os error 123)
  const data = Deno.readFileSync(path);
                    ^
    at Object.readFileSync (deno:runtime/js/40_read_file.js:11:16)
    at readFileSync (https://deno.land/std@0.153.0/node/_fs/_fs_readFile.ts:96:21)
    at https://esm.sh/v94/@surma/rollup-plugin-off-main-thread@2.2.3/deno/rollup-plugin-off-main-thread.js:2:1681
    at https://esm.sh/v94/@surma/rollup-plugin-off-main-thread@2.2.3/deno/rollup-plugin-off-main-thread.js:2:1211
    at https://esm.sh/v94/@surma/rollup-plugin-off-main-thread@2.2.3/deno/rollup-plugin-off-main-thread.js:8:1841
```

## Additional info

- **esm.sh version**: v94
- **Deno version**: 1.25.2

**Comment by UPL123** [comment]
Oops, alredy exists #157
