### ISSUE TITLE
Failed to import - `@aws-sdk/client-s3`

### ISSUE THREAD

**Issue by josephrocca** [ije/esm.sh#439]
## Failing module

- **GitHub**: https://github.com/aws/aws-sdk-js-v3
- **npm**: https://www.npmjs.com/package/@aws-sdk/client-s3

```js
import { S3Client, PutObjectCommand } from "https://esm.sh/@aws-sdk/client-s3@3.198.0/dist-es/index.js";
```

## Error message

After running `deno run` I got this:

```
error: Import 'https://esm.sh/v96/@aws-sdk/client-s3@3.198.0/deno/package.json.js' failed: 500 Internal Server Error
    at https://esm.sh/v96/@aws-sdk/client-s3@3.198.0/deno/dist-es/runtimeConfig.js:2:85
```

## Additional info

- **esm.sh version**: `v96` (also tested in `v95` and `v94`)
- **Deno version**: 1.27.0

**Comment by talentlessguy** [comment]
new error:

```
import { S3Client, PutObjectCommand } from "https://esm.sh/@aws-sdk/client-s3@3.198.0/dist-es/index.js";
Uncaught ReferenceError: window is not defined
    at https://esm.sh/v135/aws-crt@1.22.0/denonext/aws-crt.mjs:17:1093
    at https://esm.sh/v135/aws-crt@1.22.0/denonext/aws-crt.mjs:17:458
    at https://esm.sh/v135/aws-crt@1.22.0/denonext/aws-crt.mjs:26:39777
    at https://esm.sh/v135/aws-crt@1.22.0/denonext/aws-crt.mjs:17:458
    at https://esm.sh/v135/aws-crt@1.22.0/denonext/aws-crt.mjs:26:40455
```
