### ISSUE TITLE
Failed to import - https://esm.sh/jsdom@19.0.0?no-check&pin=v64

### ISSUE THREAD

**Issue by zuisong** [ije/esm.sh#467]
## Failing module

- **GitHub**: 
- **npm**:

```js
 https://esm.sh/jsdom@19.0.0?no-check&pin=v64
```

## Error message

After `onload` I got this:

```
{"error":{"status":500,"message":"Internal Server Error"}}
```

## Additional info

- **esm.sh version**: v66
- **Browser version**:

**Comment by ije** [comment]
<img width="626" alt="Screenshot 2022-12-18 at 23 21 03" src="https://user-images.githubusercontent.com/2883484/208306314-4d4653de-912d-410c-a76b-5eb83969f59c.png">
seems it works for me

**Comment by zuisong** [comment]
https://github.com/zuisong/notion-kroki/actions/runs/3562551219/attempts/1 
https://github.com/zuisong/notion-kroki/actions/runs/3562551219


three week ago, it works fine.
Today , I try to re run same CI， it does not works. And the code does not changes.

**Comment by ije** [comment]
please try to update the `deno.lock`

**Comment by zuisong** [comment]
```
    error: Error: Not implemented: isContext
      throw new Error(message);
            ^
        at notImplemented (https://deno.land/std@0.165.0/node/_utils.ts:23:9)
        at Object.isContext (https://deno.land/std@0.165.0/node/vm.ts:62:3)
        at new xfe (https://esm.sh/v64/jsdom@19.0.0/deno/jsdom.js:800:8467)
        at _3.createWindow (https://esm.sh/v64/jsdom@19.0.0/deno/jsdom.js:800:6201)
        at new ey (https://esm.sh/v64/jsdom@19.0.0/deno/jsdom.js:800:23450)
        at init (file:///Users/chen/mydata/notion-kroki/test/common/jdsom-env-init.ts:4:15)
        at Object.<anonymous> (file:///Users/chen/mydata/notion-kroki/test/jsdom_test.ts:8:5)
        at Function.runTest (https://deno.land/std@0.168.0/testing/_test_suite.ts:339:26)
        at fn (https://deno.land/std@0.168.0/testing/_test_suite.ts:316:37)
```

remove deno.lock and try to run test again, I get this error.

**Comment by zuisong** [comment]
what should I do if I want get the version of three week ago ?
